'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function decorate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon))}
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function safeURL(v){try{let u=new URL(v);return u.protocol==='https:'?u.href:''}catch{return ''}}
const memory={};const storage={get(k,d){try{let v=localStorage.getItem('axsimaros.'+k);return v?JSON.parse(v):d}catch{return memory[k]??d}},set(k,v){memory[k]=v;try{localStorage.setItem('axsimaros.'+k,JSON.stringify(v))}catch{}}};
let bookmarks=new Set(storage.get('bookmarks',[]).filter(x=>ARTICLES.some(a=>a.id===x))),read=new Set(storage.get('read',[]).filter(x=>ARTICLES.some(a=>a.id===x)));
let preferences=storage.get('preferences',{motion:matchMedia('(prefers-reduced-motion: reduce)').matches,grid:true,labels:true});
let engines=[],sim=null,currentMode='solar',page='explore',libraryFilter='all',libraryView='grid',newsFilter='all',news=SEED_NEWS.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)),feedLoaded=false,loading=false;
let lastFocus=null;
decorate();
$('#today').textContent=new Intl.DateTimeFormat('en',{day:'2-digit',month:'long',year:'numeric'}).format(new Date()).toUpperCase();
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3000)}
function openDialog(id){lastFocus=document.activeElement;$('#'+id).showModal()}
function closeDialog(id){$('#'+id).close();if(lastFocus?.isConnected)lastFocus.focus()}
$$('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d.id)}});d.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus()})});
function route(){let hash=location.hash.replace('#',''),[requested,mode]=hash.split('/');let allowed=['explore','simulations','news','library','saved'];page=allowed.includes(requested)?requested:'explore';$$('.page').forEach(e=>e.classList.toggle('active',e.id==='page-'+page));$$('[data-nav]').forEach(e=>{e.classList.toggle('active',e.dataset.nav===page);if(e.dataset.nav===page)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current')});$('#breadcrumb').textContent={explore:'Explore',simulations:'3D Simulations',news:'Latest news',library:'Astrophysics library',saved:'Saved discoveries'}[page];$('#sidebar').classList.remove('open');$('#mobile-menu').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'});document.body.classList.toggle('simulation-active',page==='simulations');if(page==='simulations'){initSim();if(mode&&MODES.some(m=>m.id===mode))setMode(mode);requestAnimationFrame(()=>sim?.resize())}if(page==='news'&&!feedLoaded){feedLoaded=true;refreshNews()}if(page==='saved')renderSaved();document.title=$('#breadcrumb').textContent+' · Axsimaros Astrophysics Lab'}
window.addEventListener('hashchange',route);
function renderHome(){let featured=['solar','blackhole','galaxy'];$('#home-sims').innerHTML=featured.map(id=>{let m=MODES.find(x=>x.id===id);return `<button class="sim-card" data-sim="${id}" aria-label="Launch ${m.title} in 3D"><div class="card-visual"><canvas data-preview="${id}" aria-hidden="true"></canvas><span class="pill">INTERACTIVE 3D</span><span class="arrow-circle">${icon('arrow')}</span></div><div class="card-body"><h3>${m.title}</h3><p>${m.desc}</p><div class="card-footer"><span class="tiny-dot"></span>${m.tag}<span>Explore ${icon('arrow')}</span></div></div></button>`}).join('');$('#home-news').innerHTML=SEED_NEWS.slice(0,3).map((n,i)=>`<a class="news-mini" href="${n.url}" target="_blank" rel="noopener"><div class="news-mini-art space-art art-${i}" aria-hidden="true"></div><div><div class="news-meta"><b>${n.source}</b>· ${dateLabel(n.date)}</div><h3>${n.title}</h3></div>${icon('external')}</a>`).join('');
 $$('[data-preview]').forEach(c=>{try{let e=new Universe3D(c,{mode:c.dataset.preview});e.paused=preferences.motion;e.time=110;e.speed=0;e.cinematic=!preferences.motion;if(e.mode==='solar'){e.focus=true;e.selected='Saturn';e.distance=7;e.pitch=.3;let pos=e.orbit(5,e.time);e.az=Math.atan2(-pos[0],-pos[2])+.6}else if(e.mode==='blackhole'){e.distance=25;e.pitch=.075}else{e.distance=46;e.pitch=.65}e.cameraAz=e.az;e.cameraPitch=e.pitch;e.cameraDistance=e.distance;engines.push(e)}catch{c.parentElement.classList.add('space-art')}});
}
function initSim(){if(sim)return;try{sim=new Universe3D($('#universe'),{mode:currentMode,interactive:true,labels:$('#object-labels')});sim.paused=preferences.motion;sim.showLabels=preferences.labels;sim.onSelect=name=>{if(name==='Sun'){sim.selected='Earth';return}renderInspector()};sim.onZoom=updateZoom;sim.onFrame=updateLabHUD;engines.push(sim);setMode(currentMode)}catch(e){$('#viewport').classList.add('no-webgl');console.error('3D initialization failed:',e)}}
function setMode(id){currentMode=id;let m=MODES.find(x=>x.id===id);if(sim&&!sim.failed){sim.setMode(id);sim.showLabels=$('#show-labels').checked;sim.paths=$('#show-orbits').checked;sim.grid=$('#show-grid').checked;sim.speed=id==='binary'?1000:id==='solar'?8:12;sim.cinematic=$('#cinematic').checked;sim.exposure=Number($('#exposure').value);sim.bloom=Number($('#bloom').value);sim.gridStyle=Number($('#grid-style').value);$('#speed').value=Math.log(sim.speed/.05)/Math.log(100000)*100;updateZoom(sim.distance);updatePlayback();renderInspector();}$('#mode-tabs').innerHTML=MODES.map(x=>`<button class="mode-tab ${x.id===id?'active':''}" data-mode="${x.id}" aria-pressed="${x.id===id}">${icon(x.icon)}${x.short}</button>`).join('');$('#scene-title').textContent=m.title;$('#scene-sub').textContent=m.subtitle;updateModelNote();renderScenePresets();$('#sim-about').innerHTML=m.about.map(([h,p])=>`<div class="info-tile"><h4>${h}</h4><p>${p}</p></div>`).join('');$('#speed-value').textContent=speedLabel(sim?.speed||40);if(sim?.failed)$('#inspector').innerHTML=`<div class="eyebrow">EXPLORE THE SCIENCE</div><h3>${m.title}</h3><p>${m.desc}</p><button class="text-link" data-article="${m.article}">Read the explanation ${icon('arrow')}</button>`;}
function speedLabel(v){return currentMode==='solar'||currentMode==='binary'?(v<10?v.toFixed(2):Math.round(v).toLocaleString())+' days / sec':(v/12).toFixed(1)+'× motion'}
function updateZoom(d){$('#zoom').value=Math.log(d/2.3)/Math.log(650/2.3)*100;$('#zoom-value').textContent=d.toFixed(1)+' units'}
function updatePlayback(){if(!sim)return;$('#pause-btn').innerHTML=icon(sim.paused?'play':'pause');$('#pause-btn').setAttribute('aria-label',sim.paused?'Play simulation':'Pause simulation');$('#play-status').textContent=sim.paused?'SIMULATION PAUSED':'SIMULATION RUNNING'}
$('#speed').addEventListener('input',e=>{if(!sim||sim.failed)return;sim.speed=.05*Math.pow(100000,Number(e.target.value)/100);$('#speed-value').textContent=speedLabel(sim.speed)});$('#zoom').addEventListener('input',e=>{if(!sim||sim.failed)return;sim.distance=2.3*Math.pow(650/2.3,Number(e.target.value)/100);updateZoom(sim.distance)});$('#show-orbits').addEventListener('change',e=>{if(sim)sim.paths=e.target.checked});$('#show-grid').addEventListener('change',e=>{if(sim)sim.grid=e.target.checked});$('#show-labels').addEventListener('change',e=>{if(sim)sim.showLabels=e.target.checked});
function dateLabel(d){let date=new Date(d);return Number.isNaN(date.getTime())?'Date unavailable':new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(date)}
function renderNews(){let q=$('#news-search').value.toLowerCase().trim(),items=news.filter(n=>(newsFilter==='all'||(n.topic+' '+n.title+' '+n.summary+' '+n.source).toLowerCase().includes(newsFilter))&&[n.title,n.summary,n.source].join(' ').toLowerCase().includes(q));$('#news-grid').innerHTML=items.map((n,i)=>`<article class="news-card"><div class="space-art art-${i%3}">${n.image?`<img src="${escapeHTML(safeURL(n.image))}" alt="" loading="lazy" referrerpolicy="no-referrer">`:''}<span class="news-art-label">${n.image?'Publisher image':'Decorative space illustration'}</span></div><div class="card-body"><div class="news-meta"><b>${escapeHTML(n.source)}</b><span>· ${dateLabel(n.date)}</span></div><h3>${escapeHTML(n.title)}</h3><p>${escapeHTML(n.summary)}</p><a class="text-link" href="${escapeHTML(safeURL(n.url))}" target="_blank" rel="noopener">Read at ${escapeHTML(n.source)} ${icon('external')}</a></div></article>`).join('')||`<div class="empty-state"><h3>No signals in this view.</h3><p>Try another source or search. Official newsrooms are linked above.</p></div>`;$$('#news-grid img').forEach(img=>img.addEventListener('error',()=>{img.nextElementSibling.textContent='Decorative space illustration';img.remove()},{once:true}))}
async function refreshNews(){if(loading)return;loading=true;$('#refresh-news').disabled=true;$('#feed-status').textContent='Connecting to the space news feed…';let controller=new AbortController(),timer=setTimeout(()=>controller.abort(),11000);try{let response=await fetch('https://api.spaceflightnewsapi.net/v4/articles/?limit=60&ordering=-published_at',{signal:controller.signal});if(!response.ok)throw Error('Feed unavailable');let data=await response.json();if(!Array.isArray(data.results))throw Error('Unrecognized feed');let items=data.results.filter(n=>safeURL(n.url)&&n.title&&Number.isFinite(Date.parse(n.published_at))).map(n=>({id:String(n.id),title:String(n.title).slice(0,250),summary:String(n.summary||'Read the full report at the original source.').slice(0,420),source:String(n.news_site||'Space news').slice(0,90),topic:'',date:n.published_at,url:n.url,image:safeURL(n.image_url)}));if(!items.length)throw Error('Empty feed');news=items.sort((a,b)=>new Date(b.date)-new Date(a.date));let stamp=new Date().toISOString();storage.set('news-cache',{items:news,stamp});$('#feed-status').textContent='Live feed loaded · '+news.length+' articles · Checked '+new Date().toLocaleString()+'. Refresh for newer stories.';}catch{let cached=storage.get('news-cache',null);if(cached?.items?.length&&cached.stamp){news=cached.items.filter(n=>safeURL(n.url));$('#feed-status').textContent='Live feed unavailable. Showing cached articles retrieved '+new Date(cached.stamp).toLocaleString()+'. Open an official newsroom above for current updates.'}else{news=SEED_NEWS.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));$('#feed-status').textContent='Live feed unavailable. Showing selected articles checked 16 September 2026. Open an official newsroom above for current updates.'}}finally{clearTimeout(timer);loading=false;$('#refresh-news').disabled=false;renderNews()}}
$('#news-search').addEventListener('input',renderNews);
function articleCard(a){let saved=bookmarks.has(a.id);return `<article class="learn-card"><button class="learn-art" data-article="${a.id}" style="--accent:${a.color}" aria-label="Read ${a.title}">${icon(a.icon)}</button><div class="card-body"><div class="news-meta"><b style="color:${a.color}">${a.category.toUpperCase()}</b><span>· ${a.minutes} MIN READ</span></div><h3><button data-article="${a.id}" style="background:none;padding:0;text-align:left;font:inherit">${a.title}</button></h3><p>${a.desc}</p><div class="learn-card-foot"><span class="${read.has(a.id)?'read-tag':'level'}">${read.has(a.id)?'✓ Explored':a.level}</span><button class="bookmark ${saved?'saved':''}" data-bookmark="${a.id}" aria-label="${saved?'Unsave':'Save'} ${a.title}" aria-pressed="${saved}">${icon('bookmark')}</button></div></div></article>`}
function renderLibrary(){let q=$('#library-search').value.toLowerCase().trim(),items=ARTICLES.filter(a=>(libraryFilter==='all'||a.category===libraryFilter)&&[a.title,a.desc,a.category].join(' ').toLowerCase().includes(q));$('#library-grid').innerHTML=items.map(articleCard).join('')||'<div class="empty-state"><h3>No matching topics.</h3><p>Try a broader search or choose All topics.</p></div>';$('#library-grid').classList.toggle('list-view',libraryView==='list');$('#progress-label').textContent=read.size+' of '+ARTICLES.length+' explored';$('#progress-bar').style.width=(read.size/ARTICLES.length*100)+'%'}
function renderSaved(){$('#saved-grid').innerHTML=ARTICLES.filter(a=>bookmarks.has(a.id)).map(articleCard).join('')||`<div class="empty-state">${icon('bookmark')}<h3>Your next discovery belongs here.</h3><p>Save a library topic with the bookmark icon, then return whenever curiosity calls.</p><a href="#library" class="btn primary" style="margin-top:20px">Explore the library ${icon('arrow')}</a></div>`}
function openArticle(id){let a=ARTICLES.find(x=>x.id===id);if(!a)return;$('#article-content').innerHTML=`<div class="eyebrow">${a.category} · ${a.minutes} MIN READ</div><h2>${a.title}</h2><p>${a.intro}</p><div class="article-diagram" aria-hidden="true">${icon(a.icon)}</div>${a.sections.map(([t,p])=>`<h3>${t}</h3><p>${p}</p>`).join('')}<div class="formula">${a.formula}<small>${a.formulaNote}</small></div><div class="article-actions">${a.simulation?`<button class="btn primary" data-sim="${a.simulation}">${icon('orbit')}Try it in 3D</button>`:''}<a class="btn" href="https://www.youtube.com/results?search_query=${encodeURIComponent(a.video)}" target="_blank" rel="noopener">${icon('play')}Find explainer videos</a><button class="btn" id="mark-read" data-read="${a.id}">${icon(read.has(a.id)?'check':'book')}${read.has(a.id)?'Explored':'Mark as explored'}</button><button class="btn" data-bookmark="${a.id}">${icon('bookmark')}<span id="article-save-label">${bookmarks.has(a.id)?'Saved':'Save topic'}</span></button></div><p class="article-source">Further reading: <a href="${a.source}" target="_blank" rel="noopener">${a.sourceName} ↗</a><br>Explanations are introductory; formula assumptions are stated above.</p>`;openDialog('article-dialog');$('#article-dialog').scrollTop=0}
function toggleBookmark(id){if(bookmarks.has(id)){bookmarks.delete(id);toast('Removed from saved discoveries')}else{bookmarks.add(id);toast('Added to your saved discoveries')}storage.set('bookmarks',[...bookmarks]);renderLibrary();renderSaved();if($('#article-save-label'))$('#article-save-label').textContent=bookmarks.has(id)?'Saved':'Save topic'}
$('#library-search').addEventListener('input',renderLibrary);
function renderSearch(){let q=$('#global-search').value.toLowerCase().trim();let matches=[...MODES.map(m=>({id:m.id,title:m.title,desc:m.short+' '+m.desc,kind:'3D simulation',icon:m.icon})),...ARTICLES.map(a=>({...a,kind:'Library article'}))].filter(x=>!q||[x.title,x.desc].join(' ').toLowerCase().includes(q)).slice(0,q?20:8);$('#search-results').innerHTML=matches.map(m=>`<button class="search-result" ${m.kind==='3D simulation'?'data-sim':'data-article'}="${m.id}">${icon(m.icon)}<div>${m.title}<small>${m.kind}</small></div><span>↗</span></button>`).join('')||'<div class="search-empty">No matches yet. Try “gravity”, “star”, or “planet”.</div>'}
$('#global-search').addEventListener('input',renderSearch);
function applyPreferences(resetPlayback=false){document.body.classList.toggle('no-motion',preferences.motion);document.body.classList.toggle('no-background-grid',!preferences.grid);$('#reduce-motion').checked=preferences.motion;$('#background-grids').checked=preferences.grid;$('#default-labels').checked=preferences.labels;$('#show-labels').checked=preferences.labels;engines.forEach(e=>{if(resetPlayback)e.paused=preferences.motion;e.showLabels=preferences.labels});updatePlayback();storage.set('preferences',preferences)}
$('#reduce-motion').addEventListener('change',e=>{preferences.motion=e.target.checked;applyPreferences(true)});$('#background-grids').addEventListener('change',e=>{preferences.grid=e.target.checked;applyPreferences()});$('#default-labels').addEventListener('change',e=>{preferences.labels=e.target.checked;applyPreferences()});
$('#mobile-menu').addEventListener('click',()=>{$('#sidebar').classList.toggle('open');$('#mobile-menu').setAttribute('aria-expanded',$('#sidebar').classList.contains('open'))});
document.addEventListener('click',async e=>{let b=e.target.closest('button,[data-action]');if(!b)return;
 if(b.dataset.close){closeDialog(b.dataset.close);return}
 if(b.dataset.sim){$$('dialog[open]').forEach(d=>d.close());if(location.hash==='#simulations/'+b.dataset.sim){route()}else location.hash='simulations/'+b.dataset.sim;return}
 if(b.dataset.article){if($('#search-dialog').open)$('#search-dialog').close();openArticle(b.dataset.article);return}
 if(b.dataset.mode){setMode(b.dataset.mode);history.replaceState(null,'','#simulations/'+b.dataset.mode);return}
 if(b.dataset.bookmark){toggleBookmark(b.dataset.bookmark);return}
 if(b.dataset.read){read.add(b.dataset.read);storage.set('read',[...read]);b.innerHTML=icon('check')+'Explored';renderLibrary();renderSaved();toast('One more piece of the universe understood.');return}
 if(b.dataset.libraryFilter){libraryFilter=b.dataset.libraryFilter;$$('[data-library-filter]').forEach(x=>x.classList.toggle('active',x===b));renderLibrary();return}
 if(b.dataset.newsFilter){newsFilter=b.dataset.newsFilter;$$('[data-news-filter]').forEach(x=>x.classList.toggle('active',x===b));renderNews();return}
 if(b.dataset.view){libraryView=b.dataset.view;$$('[data-view]').forEach(x=>x.classList.toggle('active',x===b));renderLibrary();return}
 switch(b.dataset.action){case 'search':$('#global-search').value='';renderSearch();openDialog('search-dialog');$('#global-search').focus();break;case 'settings':openDialog('settings-dialog');break;case 'about':openDialog('about-dialog');break;case 'refresh':refreshNews();break;case 'pause':if(sim&&!sim.failed){sim.paused=!sim.paused;updatePlayback()}break;case 'zoom-in':if(sim){sim.distance=Math.max(2.3,sim.distance*.85);updateZoom(sim.distance)}break;case 'zoom-out':if(sim){sim.distance=Math.min(650,sim.distance*1.15);updateZoom(sim.distance)}break;case 'focus-object':if(sim){focusPlanet(sim.selected);toast('Following '+sim.selected+' · drag to look around')}break;case 'reset-camera':if(sim){cameraBookmark(currentMode==='transit'?'observer':currentMode==='blackhole'?'edge':'overview');toast('Camera reset')}break;case 'fullscreen':try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#viewport').requestFullscreen()}catch{toast('Fullscreen is unavailable in this browser. Try Theater view.')}break;}
});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#global-search').value='';renderSearch();openDialog('search-dialog');$('#global-search').focus()}if(e.key==='Escape'){$('#sidebar').classList.remove('open');$('#mobile-menu').setAttribute('aria-expanded','false')}});
document.addEventListener('fullscreenchange',()=>setTimeout(()=>sim?.resize(),70));
initLab();renderHome();renderLibrary();renderSaved();renderNews();applyPreferences();route();
