const ICONS={
compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2.5 5.5L8 16l2.5-5.5Z"/>',
orbit:'<circle cx="12" cy="12" r="3"/><ellipse cx="12" cy="12" rx="11" ry="5" transform="rotate(-30 12 12)"/><path d="M8 3c4-2 9 12 7 17"/><circle cx="20" cy="7" r="1.2" fill="currentColor"/>',
news:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 7h8M8 12h8M8 16h5"/>',
book:'<path d="M12 5C8 2 3 4 2 4v15c4-2 8-1 10 1 2-2 6-3 10-1V4c-1 0-6-2-10 1Zm0 0v15"/>',
bookmark:'<path d="M6 3h12v18l-6-4-6 4Z"/>',
sparkles:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7ZM20 2v4M18 4h4"/>',
sliders:'<path d="M4 6h7m5 0h4M4 12h2m5 0h9M4 18h10m5 0h1"/><circle cx="13" cy="6" r="2"/><circle cx="8" cy="12" r="2"/><circle cx="16" cy="18" r="2"/>',
globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18M5 7h14M5 17h14"/>',
search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
arrow:'<path d="M4 12h15m-5-5 5 5-5 5"/>',
external:'<path d="M14 3h7v7m-1-6-9 9M10 4H4v16h16v-6"/>',
play:'<path d="m8 4 12 8-12 8Z" fill="currentColor" stroke-width="0"/>',
pause:'<path d="M8 5v14M16 5v14" stroke-width="4"/>',
radio:'<circle cx="12" cy="12" r="2"/><path d="M8 8a6 6 0 0 0 0 8m8-8a6 6 0 0 1 0 8M5 5a10 10 0 0 0 0 14M19 5a10 10 0 0 1 0 14"/>',
menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
close:'<path d="m6 6 12 12M18 6 6 18"/>',
plus:'<path d="M5 12h14M12 5v14"/>',
minus:'<path d="M5 12h14"/>',
reset:'<path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/>',
expand:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>',
grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
list:'<path d="M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1"/>',
hole:'<circle cx="12" cy="12" r="4"/><ellipse cx="12" cy="12" rx="11" ry="6" transform="rotate(-20 12 12)"/><path d="M8 8c0-7 8-7 8 0m-8 8c0 7 8 7 8 0"/>',
galaxy:'<path d="M12 12c0-4 7-4 7 1 0 8-14 9-16 0C0 1 21-2 22 11M12 12c0 4-7 4-7-1 0-8 14-9 16 0"/>',
binary:'<circle cx="7" cy="9" r="4"/><circle cx="17" cy="15" r="3"/><ellipse cx="12" cy="12" rx="11" ry="6" transform="rotate(30 12 12)"/>',
wave:'<path d="M2 12c3-16 5 16 8 0s5 16 8 0 4 0 4 0"/>',
check:'<path d="m5 12 4 4L19 6"/>',
rocket:'<path d="M9 15C7 8 13 3 21 3c0 8-5 14-12 12ZM9 8H5l-3 5h6m8 2v4l-5 3v-6M7 17l-4 4"/><circle cx="16" cy="8" r="2"/>'
};
function icon(name){return '<svg viewBox="0 0 24 24" aria-hidden="true">'+(ICONS[name]||ICONS.sparkles)+'</svg>'}
const MODES=[
 {id:'solar',title:'The Solar System',short:'Solar system',subtitle:'A CELESTIAL NEIGHBORHOOD',icon:'orbit',desc:'Eight planets. One star. Endless perspectives.',tag:'ORBITAL MECHANICS',article:'orbits',note:'Keplerian orbits use approximate real orbital periods and eccentricities. Distances are compressed and body sizes enlarged; orbital phases are illustrative, not today’s sky. Mutual perturbations and moons are omitted.',about:[['A cosmic clock','Move the time slider and watch Mercury race around the Sun while the outer planets take their time.'],['Change your perspective','Drag to move above or below the orbital plane. Turn on the grid to make the 3D depth visible.'],['Follow the ellipses','The Sun sits at a focus of each orbit. A planet moves faster near its closest approach.']]},
 {id:'blackhole',title:'Beyond the Event Horizon',short:'Black hole',subtitle:'WHERE GRAVITY TAKES OVER',icon:'hole',desc:'Explore an accretion disk from every angle.',tag:'EXTREME GRAVITY',article:'black-holes',note:'Conceptual 3D accretion-disk model, not a general-relativistic ray tracer. The dark sphere represents the horizon, not a prediction of the observed shadow. Changing mass adjusts the conceptual scale; brightness and disk motion are artistic.',about:[['The point of no return','The event horizon marks the boundary beyond which outgoing light cannot escape to distant observers.'],['A disk that shines','The black hole emits no light from inside the horizon. Hot matter around it can radiate intensely.'],['Give it a spin','Orbit the camera to reveal the thin disk. This scene does not calculate relativistic light bending.']]},
 {id:'binary',title:'A Gravitational Duet',short:'Binary stars',subtitle:'TWO STARS · ONE CENTER OF MASS',icon:'binary',desc:'Watch two stars share a gravitational dance.',tag:'STELLAR SYSTEMS',article:'binary-stars',note:'Circular Newtonian two-body model: primary mass is 1 solar mass, separation is 10 AU. Mass ratio changes the barycenter and Keplerian period. Stellar radii, colors, and lighting are illustrative; tides and stellar evolution are omitted.',about:[['Find the balance','Both stars orbit a shared center of mass, marked by the cross at the center of the scene.'],['Change the mass ratio','A heavier companion pulls the primary farther from the barycenter. The lighter star traces the larger orbit.'],['A useful cosmic scale','Astronomers can use binary-star orbits to infer stellar masses through gravity.']]},
 {id:'galaxy',title:'A Spiral of Starlight',short:'Spiral galaxy',subtitle:'THOUSANDS OF POINTS · THREE DIMENSIONS',icon:'galaxy',desc:'Find your perspective in a sea of stars.',tag:'GALACTIC STRUCTURE',article:'galaxies',note:'Conceptual rotating 3D particle model of a spiral galaxy. Particle positions and brightness are illustrative; this is not an N-body gravity simulation, a dark-matter model, or a real galaxy catalogue.',about:[['An island of stars','Galaxies contain stars, gas, dust, and dark matter bound together by gravity.'],['From face-on to edge-on','Move the camera above the spiral arms, then rotate to see the thin stellar disk.'],['Patterns in motion','Real spiral arms are patterns in a changing disk. This simplified scene rotates the particle distribution as a whole.']]},
 {id:'nebula',title:'A Stellar Nursery',short:'Stellar nursery',subtitle:'THE BEGINNING OF SOMETHING BRIGHT',icon:'sparkles',desc:'Step inside a luminous cloud of cosmic dust.',tag:'STAR FORMATION',article:'nebulae',note:'An artistic volumetric particle cloud in real 3D. Color, cloud rotation, density, and star positions are illustrative; the scene does not simulate gas dynamics, radiative transfer, or gravitational collapse.',about:[['Made of star stuff','Cold molecular clouds contain gas and dust. Dense regions can collapse under their own gravity.'],['Look through the cloud','Orbit around the particles to see parallax and depth inside the nebula.'],['A different kind of view','Real telescope images often map invisible wavelengths to visible colors to reveal physical structure.']]},
 {id:'transit',title:'A World in the Starlight',short:'Exoplanet',subtitle:'A SMALL SHADOW · A BIG DISCOVERY',icon:'globe',desc:'Discover how a planet gives itself away.',tag:'EXOPLANET DETECTION',article:'exoplanets',note:'Illustrative circular orbit with adjustable planet-to-star radius. The displayed maximum transit depth uses (Rp/Rs)² for a fully overlapping opaque planet and uniform stellar brightness. The formula is independent of camera angle; limb darkening is omitted.',about:[['Follow the shadow','Return to the default camera and watch the planet pass across the face of its host star.'],['Size matters','Double the planet-to-star radius ratio and the ideal transit depth becomes four times larger.'],['A clue, not a photograph','A repeated dip in starlight can reveal a planet even when it is too distant to image directly.']]}
];
const ARTICLES=[
 {id:'gravity',title:'Gravity: the invisible architect',category:'Fundamentals',level:'Start here',minutes:3,icon:'orbit',color:'#ba9cfc',desc:'Why things fall, and why planets keep missing the Sun.',intro:'Every object with mass attracts every other object with mass. Gravity is gentle between everyday objects, but it shapes stars, planetary systems, and galaxies on cosmic scales.',sections:[['Falling around a world','An orbiting object is falling under gravity while moving sideways. With the right motion, its path keeps curving around the body rather than hitting it. There is gravity in orbit: astronauts float because they and their spacecraft fall together.'],['Distance makes a difference','Newton’s law says the gravitational force increases with the two masses and decreases with the square of their separation. Double the distance and the force becomes one quarter as large.'],['A deeper picture','General relativity describes gravity through spacetime curvature. Newton’s law remains an excellent approximation for many slow-moving systems with weak gravitational fields.']],formula:'F = G m₁m₂ / r²',formulaNote:'G: gravitational constant · r: separation between the centers of spherical bodies',source:'https://science.nasa.gov/solar-system/',sourceName:'NASA Solar System Exploration',video:'NASA gravity orbits explained',simulation:'solar'},
 {id:'orbits',title:'The quiet elegance of orbits',category:'Fundamentals',level:'Beginner',minutes:3,icon:'orbit',color:'#99b8ff',desc:'Ellipses, orbital speeds, and Kepler’s remarkable rules.',intro:'An ideal two-body orbit under Newtonian gravity is a conic section. Bound planetary orbits are ellipses, with the Sun approximately at one focus.',sections:[['Three useful rules','Kepler’s first law describes the elliptical path. The second says that the line from a planet to the Sun sweeps out equal areas in equal times: the planet moves faster when closer to the Sun.'],['A clock written in distance','The third law links orbital period to orbital size. For planets orbiting the Sun, period squared is approximately proportional to the cube of the semimajor axis.'],['Reading the simulator','Our simulator preserves approximate periods and eccentricities while compressing the spacing between planets. Use it to compare motion, rather than to measure actual distances on screen.']],formula:'P² ≈ a³',formulaNote:'Solar-mass host · P in Earth years · a in astronomical units',source:'https://science.nasa.gov/solar-system/',sourceName:'NASA Solar System Exploration',video:'NASA Kepler laws planetary motion',simulation:'solar'},
 {id:'light',title:'Light is a cosmic messenger',category:'Fundamentals',level:'Beginner',minutes:3,icon:'wave',color:'#82d9c7',desc:'What wavelengths and spectra can tell us about distant worlds.',intro:'Almost everything we learn about distant stars starts with light. Visible light is only a narrow slice of the electromagnetic spectrum, between infrared and ultraviolet.',sections:[['One phenomenon, many wavelengths','Radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, and gamma rays are all electromagnetic radiation. They travel at the same speed in vacuum, but carry different energies per photon.'],['A stellar fingerprint','Atoms and molecules absorb or emit light at characteristic wavelengths. A spectrum can reveal composition, motion, and clues about temperature. Different instruments uncover different parts of the story.'],['A time machine in every telescope','Light travels at a finite speed. When we observe a star 100 light-years away, we see light that traveled for roughly 100 years. A light-year is a distance, not a duration.']],formula:'c = λ f',formulaNote:'c: light speed in vacuum · λ: wavelength · f: frequency',source:'https://science.nasa.gov/ems/',sourceName:'NASA: The Electromagnetic Spectrum',video:'NASA electromagnetic spectrum explained',simulation:null},
 {id:'stars',title:'The life and light of a star',category:'Stars',level:'Beginner',minutes:3,icon:'sparkles',color:'#f2c387',desc:'From a collapsing cloud to a star that lights up the dark.',intro:'A star begins when a dense region of a gas cloud collapses. As the material falls inward, its central temperature and pressure rise. Sustained hydrogen fusion marks the start of the main sequence.',sections:[['A balancing act','Gravity pulls inward, while pressure inside the star pushes outward. Over much of a star’s life, these effects remain close to balance. Fusion supplies the energy the star radiates away.'],['Mass sets the pace','Massive stars generally shine much more brightly and use their fuel faster. Lower-mass stars can remain on the main sequence for far longer than stars like our Sun.'],['What comes next?','The later stages depend strongly on mass and environment. Sun-like stars eventually shed outer layers and leave white dwarfs. Some massive stars undergo core collapse, leaving neutron stars or black holes.']],formula:'E = mc²',formulaNote:'Fusion releases energy because the products have less total rest mass.',source:'https://science.nasa.gov/universe/stars/',sourceName:'NASA: Stars',video:'NASA life cycle stars explained',simulation:'nebula'},
 {id:'binary-stars',title:'When stars come in pairs',category:'Stars',level:'Intermediate',minutes:3,icon:'binary',color:'#98bcff',desc:'A gravitational duet reveals how much stars weigh.',intro:'In a binary system, two stars move around their shared center of mass, or barycenter. The barycenter lies closer to the more massive star.',sections:[['The balance point','The masses and distances from the barycenter balance: m₁r₁ = m₂r₂. Equal masses circle equally far from the center. If one star is much heavier, it moves in a much smaller orbit.'],['Weighing the stars','Measurements of orbital size and period can constrain the total mass. Depending on how a binary is observed, astronomers may also need distance, inclination, and spectroscopic measurements.'],['Try it in the lab','Change the companion-to-primary mass ratio. Watch both stars shift their orbits while their separation stays fixed. The model also changes their period to match the new total mass.']],formula:'m₁ r₁ = m₂ r₂',formulaNote:'r₁ and r₂ are distances from the common center of mass.',source:'https://science.nasa.gov/universe/stars/',sourceName:'NASA: Stars',video:'NASA binary stars barycenter explained',simulation:'binary'},
 {id:'nebulae',title:'Inside a stellar nursery',category:'Stars',level:'Beginner',minutes:3,icon:'sparkles',color:'#d398ed',desc:'Clouds of gas and dust can hold the seeds of future suns.',intro:'Nebulae are clouds of gas and dust. Some contain regions where new stars are forming; others are shaped by aging stars or stellar explosions.',sections:[['A nursery needs the right conditions','Stars form in dense, cold regions of molecular clouds. When gravity overcomes pressure and other support, part of a cloud can collapse. Disks and jets can develop around young stars.'],['Why the colors?','Glowing gas may emit characteristic wavelengths, while dust can scatter or absorb light. Astronomical images often assign visible colors to infrared or other invisible wavelengths. Color is a tool for showing structure.'],['Explore in three dimensions','Our particle cloud lets you move through different viewing angles. It illustrates depth; it does not calculate how a real cloud collapses or emits light.']],formula:'Cloud → Protostar → Main-sequence star',formulaNote:'A simplified pathway; not every dense clump becomes a star.',source:'https://science.nasa.gov/universe/stars/',sourceName:'NASA: Stars and star formation',video:'NASA nebula star formation Webb explained',simulation:'nebula'},
 {id:'black-holes',title:'The edge of a black hole',category:'Deep space',level:'Intermediate',minutes:4,icon:'hole',color:'#efa97c',desc:'Event horizons, glowing disks, and the limits of escape.',intro:'A black hole has a region from which light cannot escape to distant observers. Its boundary is the event horizon. The horizon is not a solid surface.',sections:[['Where the light comes from','Matter outside a black hole can form a hot accretion disk and shine strongly. Some systems also launch jets. The black hole itself does not send ordinary light outward from inside its horizon.'],['A scale set by mass','For a nonrotating, uncharged black hole, the Schwarzschild radius is proportional to mass. A black hole with ten solar masses has a Schwarzschild radius of roughly 30 kilometers.'],['Why the view is strange','Real light paths curve in strong gravity. The observed shadow and distorted disk require relativistic modeling. Our 3D scene shows the broad arrangement, not an exact optical prediction.']],formula:'rₛ = 2GM / c²',formulaNote:'Schwarzschild radius for a nonrotating, uncharged black hole.',source:'https://science.nasa.gov/universe/black-holes/',sourceName:'NASA: Black Holes',video:'NASA black hole event horizon accretion disk explained',simulation:'blackhole'},
 {id:'galaxies',title:'Islands in the cosmic ocean',category:'Deep space',level:'Beginner',minutes:3,icon:'galaxy',color:'#af9aef',desc:'Spiral arms, stellar disks, and our place in the Milky Way.',intro:'A galaxy is a gravitationally bound system containing stars, gas, dust, and dark matter. Galaxies range from small dwarfs to enormous systems with vast stellar populations.',sections:[['Many shapes, many histories','Spiral galaxies have disks and recognizable arms. Elliptical galaxies look smoother, and irregular galaxies lack a simple overall shape. Interactions and mergers can reshape galaxies over time.'],['Reading a spiral','A spiral’s bright arms often include young stars and star-forming gas. A central bulge can contain an older stellar population. The visible disk occupies only part of a much larger galactic system.'],['Where we live','The Sun belongs to the Milky Way. We view our galaxy from inside its disk, which makes mapping its overall structure a challenge. The lab’s galaxy is an illustrative model, not a map of the Milky Way.']],formula:'Stars + gas + dust + dark matter',formulaNote:'A galaxy is much more than the starlight we can see.',source:'https://science.nasa.gov/universe/galaxies/',sourceName:'NASA: Galaxies',video:'NASA Milky Way spiral galaxies explained',simulation:'galaxy'},
 {id:'expansion',title:'A universe that keeps growing',category:'Deep space',level:'Intermediate',minutes:3,icon:'galaxy',color:'#87c5e8',desc:'Redshift, cosmic distances, and the expansion of space.',intro:'On large scales, the distances between unbound galaxies tend to increase as the universe expands. This does not mean every nearby object moves away from every other one.',sections:[['Light stretches too','As light travels through expanding space, its wavelength stretches. This cosmological redshift helps astronomers study the expansion history of the universe.'],['A local approximation','For sufficiently nearby galaxies in the cosmic flow, recession speed is approximately proportional to distance. At very large distances, the relationship needs a cosmological model rather than a simple linear conversion.'],['What stays together?','Gravity can keep systems such as galaxies and the solar system bound. Expansion is a large-scale behavior, not an everyday stretching of rulers, planets, or people.']],formula:'v ≈ H₀ d',formulaNote:'Hubble–Lemaître law, a nearby-universe approximation.',source:'https://science.nasa.gov/universe/overview/',sourceName:'NASA: The Universe',video:'NASA expanding universe redshift explained',simulation:'galaxy'},
 {id:'exoplanets',title:'Finding worlds we cannot see',category:'Worlds',level:'Beginner',minutes:3,icon:'globe',color:'#7cdbc7',desc:'A tiny dip in starlight can announce a whole new world.',intro:'An exoplanet is a planet outside our solar system. Astronomers discover many of them indirectly, by measuring changes in the light of their host stars.',sections:[['The transit method','If the geometry lines up, a planet passes in front of its star and blocks a small fraction of the starlight. Repeated dips help reveal the planet’s orbital period.'],['A shadow tells a size story','For a uniformly bright star and a fully overlapping opaque planet, the fractional drop is approximately the square of the radius ratio. A ratio of 0.1 gives a 1% dip.'],['Other ways to find a world','The radial-velocity method detects a star’s motion toward and away from us. Direct imaging and gravitational microlensing reveal other kinds of planets. Each technique has selection effects.']],formula:'Transit depth ≈ (Rₚ / R★)²',formulaNote:'Ideal full transit · ignores limb darkening and grazing geometry.',source:'https://science.nasa.gov/exoplanets/',sourceName:'NASA: Exoplanets',video:'NASA exoplanet transit method explained',simulation:'transit'},
 {id:'planets',title:'Rocky worlds and giant planets',category:'Worlds',level:'Beginner',minutes:3,icon:'globe',color:'#f0bc86',desc:'The eight planets are a surprisingly varied family.',intro:'The four inner planets are rocky worlds. Farther out, Jupiter and Saturn are gas giants, while Uranus and Neptune are usually classified as ice giants.',sections:[['A story of ingredients','Planets formed from material in the disk around the young Sun. Temperature, available material, growth, and migration all helped shape the resulting worlds.'],['No single scale tells the story','Size, mass, density, atmosphere, and temperature describe different things. A large radius does not guarantee a solid surface. Planetary environments are more diverse than a row of circles can show.'],['Explore the family','Choose a planet in the simulator to compare its approximate diameter, orbital period, and distance. Display sizes are enlarged so small rocky planets remain visible.']],formula:'1 AU ≈ 149.6 million km',formulaNote:'An astronomical unit is a standard scale for solar-system distances.',source:'https://science.nasa.gov/solar-system/',sourceName:'NASA Solar System Exploration',video:'NASA solar system planets explained',simulation:'solar'},
 {id:'telescopes',title:'New eyes on the universe',category:'Worlds',level:'Beginner',minutes:3,icon:'radio',color:'#9cc6f9',desc:'Why astronomers observe with more than one kind of telescope.',intro:'A telescope collects and focuses radiation. Different instruments are designed for different wavelengths, giving astronomers complementary views of the same object.',sections:[['A bigger light bucket','A larger collecting area captures more light, helping reveal fainter objects. Angular resolution also depends on aperture and wavelength, along with atmosphere, optics, and instrument design.'],['Why go to space?','Earth’s atmosphere absorbs much of the electromagnetic spectrum and blurs many ground-based views. Space observatories avoid these limits, while ground observatories can host very large and upgradeable instruments.'],['A team of perspectives','Webb observes primarily in infrared. Hubble observes ultraviolet, visible, and some near-infrared light. Chandra studies X-rays. Combining their observations can connect cold dust, stars, and energetic gas.']],formula:'Angular resolution ∝ wavelength / aperture',formulaNote:'A simplified diffraction limit; practical observing adds other constraints.',source:'https://science.nasa.gov/mission/webb/',sourceName:'NASA: James Webb Space Telescope',video:'NASA Webb Hubble Chandra wavelengths explained',simulation:null}
];
const SEED_NEWS=[
 {id:'webb-ic348',title:'Webb reveals a remarkable panorama of star formation',summary:'A new view of IC 348 reveals young stars, jets, and unusually low-mass brown dwarfs in a nearby stellar nursery.',source:'NASA',topic:'nasa',date:'2026-09-15T12:00:00Z',url:'https://science.nasa.gov/missions/webb/nasas-webb-reveals-dynamic-panorama-of-star-formation/'},
 {id:'roman',title:'Roman’s primary instrument powers on',summary:'NASA reports on activation of the Roman Space Telescope’s main instrument and checks of its coronagraph.',source:'NASA',topic:'nasa',date:'2026-09-15T12:00:00Z',url:'https://science.nasa.gov/blogs/roman/2026/09/15/nasa-activates-romans-primary-instrument-checks-out-coronagraph/'},
 {id:'chandra',title:'Chandra uncovers mysterious X-ray sources',summary:'A newly studied population of unusually soft X-ray sources raises questions about compact objects and their companion stars.',source:'NASA',topic:'nasa',date:'2026-09-09T12:00:00Z',url:'https://science.nasa.gov/missions/chandra/nasas-chandra-unveils-mysterious-x-ray-objects/'},
 {id:'starship',title:'SpaceX outlines an orbital goal for Starship Flight 14',summary:'Industry reporting describes plans for an orbital test and satellite deployment. The proposed launch timing remains subject to approval.',source:'MarketWatch',topic:'spacex',date:'2026-09-16T00:00:00Z',url:'https://www.marketwatch.com/story/spacexs-starship-is-finally-set-for-orbit-a-lot-is-riding-on-its-success-764219b3'},
 {id:'tno',title:'Distant icy worlds retain clues to their past',summary:'Hubble and Webb observations investigate small objects beyond Neptune and the history recorded in their surfaces.',source:'NASA',topic:'nasa',date:'2026-09-08T12:00:00Z',url:'https://science.nasa.gov/missions/hubble/nasas-hubble-webb-find-far-out-solar-system-objects-remember-past/'},
 {id:'falcon',title:'Falcon 9 carries a classified Space Force payload',summary:'Reporting covers a SpaceX launch from Vandenberg and the company’s continued role in national security missions.',source:'Barron’s',topic:'spacex',date:'2026-09-11T00:00:00Z',url:'https://www.barrons.com/articles/spacex-stock-price-secret-space-force-launch-b1835c10'}
];
/* Observatory II model descriptions and limits. */
Object.assign(MODES[0],{desc:'Image-mapped worlds, moons, atmospheres, and Keplerian motion.',note:'Approximate Keplerian periods, eccentricities, and orbital inclinations; phases are illustrative, not current ephemerides. Surface rotation, body sizes, and moon separation are adjusted for visibility. Velocity readouts use the vis-viva equation with solar GM. No planetary perturbations are solved.',about:[['From worlds to systems','Follow Earth to see the Moon, Jupiter to find four Galilean moons, or Saturn to inspect its rings and Titan. Surface maps bring each world into focus.'],['An unbounded coordinate plane','The grid is evaluated along camera rays and adapts its spacing with zoom. Choose Cartesian or polar coordinates; there is no rectangular grid edge.'],['Distance is a choice','Compact mode compresses orbital spacing logarithmically. Linear mode uses a common distance scale for planetary semimajor axes; visible body sizes remain enlarged.']]});
Object.assign(MODES[1],{desc:'Follow bent light through a luminous, turbulent disk.',note:'Physically inspired ray integration with an approximate bending force and Doppler brightness law. This is not a validated Schwarzschild or Kerr geodesic solver. The disk is prescribed, not an MHD simulation. Coordinates are normalized to rₛ; the photon-sphere and ISCO readouts are theoretical nonrotating values.',about:[['Follow a ray, change the view','The shader steps rays through an approximate gravitational field and samples disk intersections. Changing the camera changes which parts of the disk appear above and below the shadow.'],['Motion changes brightness','The approaching side is boosted by a Doppler-inspired brightness factor. Switch the effect off to compare it with a symmetric disk.'],['A model with stated limits','Mass sets the physical scale through rₛ = 2GM/c². The rendering uses an approximation for interaction speed, so it is not a substitute for research ray tracing.']]});
Object.assign(MODES[2],{desc:'A two-body orbit with a changing radial-velocity signal.',note:'Circular Newtonian two-body model: primary mass 1 M☉, separation 10 AU. Mass ratio determines the barycenter and period. Radial velocity is projected along the camera’s line of sight. Stellar radii, surface maps, temperatures, and colors are illustrative; no tides or stellar evolution.',about:[['Watch the shared center','Both stars orbit the barycenter. Changing the companion mass changes both orbital radii while leaving their separation fixed.'],['Turn motion into a spectrum','The primary-star radial velocity is calculated from the orbit and camera direction. A face-on view suppresses the line-of-sight signal.'],['A measured mass scale','The two-body period follows P² = a³ / (M₁ + M₂) with years, AU, and solar masses. This is the quantitative model behind the animation.']]});
Object.assign(MODES[3],{desc:'48,000 stellar tracers, illuminated arms, and dark dust lanes.',note:'An illustrative galaxy combining 48,000 advected stellar tracers, an analytic emission volume, and dust attenuation. The prescribed angular-speed law is Ω ∝ 1/(R+2) in arbitrary model units. It is not a self-gravitating N-body model, real catalogue, or calibrated surface-brightness prediction.',about:[['An integrated view','The continuous galactic volume supplies diffuse starlight; individual stellar tracers reveal structure inside the arms and central bulge.'],['A thin disk in real space','Rotate toward the disk plane to see the contrast between a thin stellar disk and the thicker central population.'],['Differential motion','Stars at different radii move at different angular speeds. The initial spiral distribution shears over time rather than rotating as a rigid object.']]});
Object.assign(MODES[4],{desc:'Ray-marched gas, absorbing dust, and embedded stars.',note:'A procedural 3D density field integrated with an illustrative emission–absorption model. Color mappings, density, star positions, and flow are artistic choices; this is not a calibrated observation, hydrodynamic simulation, or full radiative-transfer solution.',about:[['Look through a volume','Each viewing ray accumulates light while dense material absorbs part of the signal. Moving the camera changes the path through the cloud.'],['Adjust the optical depth','Increase relative density to strengthen absorption and change the balance of bright gas and dark filaments.'],['Color is an observing choice','Switch between emission-inspired and warm-dust palettes. These mappings explain structure visually; they do not claim measured spectral line intensities.']]});
Object.assign(MODES[5],{desc:'A 3D orbit paired with numerical transit photometry.',note:'Illustrative circular orbit. Photometry numerically integrates 180 stellar annuli with a linear limb-darkening law and an opaque planet. Radius ratio and impact parameter control the transit. The observer stays on +Z independently of camera motion. Stellar surface animation and time scale are illustrative.',about:[['More than a square of the radius','The simple depth ≈ (Rₚ/R★)² formula assumes uniform brightness and a full transit. This model also includes limb darkening and grazing geometries.'],['A grazing world','Raise the impact parameter until the transit becomes shallow or vanishes. It measures the projected closest approach in stellar-radius units.'],['A fixed photometric observer','The light curve belongs to an observer on the +Z axis. Orbiting the camera lets you inspect the geometry without redefining that measurement.']]});
ARTICLES.find(x=>x.id==='nebulae').sections[2][1]='The lab integrates light through a continuous three-dimensional cloud. Change density and color mapping, then orbit around it to see how the path through absorbing and emitting material changes the view.';
