/* Axsimaros — dependency-free WebGL 3D renderer. */
const TAU=Math.PI*2;
const V={sub:(a,b)=>a.map((v,i)=>v-b[i]),dot:(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{let n=Math.hypot(...a);return a.map(v=>v/(n||1))}};
const M={
 mul:(a,b)=>{let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o},
 perspective:(f,a,n,z)=>new Float32Array([1/Math.tan(f/2)/a,0,0,0,0,1/Math.tan(f/2),0,0,0,0,(z+n)/(n-z),-1,0,0,2*z*n/(n-z),0]),
 look:(eye,target)=>{let z=V.norm(V.sub(eye,target)),x=V.norm(V.cross([0,1,0],z)),y=V.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1])},
 model:(p=[0,0,0],s=1,y=0,tilt=0)=>{let c=Math.cos(y),d=Math.sin(y),a=Math.cos(tilt),b=Math.sin(tilt);return new Float32Array([c*a*s,b*c*s,-d*s,0,-b*s,a*s,0,0,d*a*s,d*b*s,c*s,0,...p,1])}
};
const PLANETS=[
 {name:'Mercury',r:.28,a:.387,e:.206,period:87.97,size:.26,color:[.61,.55,.49],kind:1,diameter:'4,879 km',fact:'The smallest planet completes an orbit in just 88 Earth days.'},
 {name:'Venus',r:.42,a:.723,e:.007,period:224.70,size:.42,color:[.87,.65,.38],kind:4,diameter:'12,104 km',fact:'A dense carbon dioxide atmosphere traps heat beneath thick clouds.'},
 {name:'Earth',r:.46,a:1,e:.017,period:365.26,size:.46,color:[.18,.44,.85],kind:2,diameter:'12,742 km',fact:'Our ocean world is the only planet currently known to host life.'},
 {name:'Mars',r:.34,a:1.524,e:.093,period:686.98,size:.34,color:[.75,.28,.14],kind:1,diameter:'6,779 km',fact:'Iron-rich minerals give the surface of Mars its rusty red color.'},
 {name:'Jupiter',r:1.05,a:5.203,e:.049,period:4332.59,size:1.05,color:[.76,.58,.39],kind:3,diameter:'139,820 km',fact:'The largest planet is a gas giant, with no solid surface like Earth’s.'},
 {name:'Saturn',r:.88,a:9.537,e:.057,period:10759.22,size:.88,color:[.85,.74,.51],kind:3,diameter:'116,460 km',fact:'Its rings contain countless pieces of ice and rock.'},
 {name:'Uranus',r:.62,a:19.191,e:.046,period:30688.5,size:.62,color:[.39,.79,.82],kind:4,diameter:'50,724 km',fact:'This ice giant rotates on its side, with an axial tilt of about 98°.'},
 {name:'Neptune',r:.61,a:30.069,e:.009,period:60182,size:.61,color:[.21,.38,.84],kind:4,diameter:'49,244 km',fact:'The most distant planet takes about 165 Earth years to orbit the Sun.'}
];
function seeded(seed=913){return()=>{seed=(Math.imul(seed,1664525)+1013904223)|0;return(seed>>>0)/4294967296}}
const PLANET_MAPS=['mercury','venus_atmosphere','earth','mars','jupiter','saturn','uranus','neptune'];
const PLANET_INCLINATIONS=[7.005,3.394,0,1.850,1.303,2.489,.773,1.770];
const PLANET_NODES=[48.33,76.68,0,49.58,100.56,113.71,74.23,131.72];
const PLANET_TILTS=[.034,177.4,23.44,25.19,3.13,26.73,97.77,28.32];
const IMAGE_CACHE=new Map();
function astroImage(url){if(!IMAGE_CACHE.has(url)){const image=new Image();image.src=url;IMAGE_CACHE.set(url,image)}return IMAGE_CACHE.get(url)}
function transitFlux(z,k,u=.6){if(z>=1+k)return 1;let total=0,blocked=0;const n=180;for(let i=0;i<n;i++){let r=(i+.5)/n,weight=r*(1-u*(1-Math.sqrt(1-r*r)));let fraction=z<1e-8?(r<k?1:0):Math.acos(Math.max(-1,Math.min(1,(r*r+z*z-k*k)/(2*r*z))))/Math.PI;total+=weight;blocked+=weight*fraction;}return Math.max(0,1-blocked/total)}
class Universe3D{
 constructor(canvas,{mode='solar',interactive=false,labels=null}={}){
  Object.assign(this,{canvas,mode,interactive,labels,time:0,visualTime:0,speed:8,paused:false,az:.42,pitch:.50,distance:64,paths:true,grid:false,gridStyle:0,showLabels:true,selected:'Earth',param:1,last:0,drag:false,focus:false,linearScale:false,lensing:true,doppler:true,density:1.1,band:0,bloom:.8,exposure:1,quality:1,impact:.25,limbDarkening:.6,cinematic:!interactive,vector:false,velAz:0,velPitch:0,disposed:false});
  this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.paused=this.reduced;const gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'});this.gl=gl;
  if(!gl){canvas.parentElement.classList.add('no-webgl');this.failed=true;return}
  this.programCache=new Map();this.enabledAttrs=new Set();this.textures=new Map();this.meshP=this.program(meshVertex,meshFragment);this.pointP=this.program(pointVertex,pointFragment);this.screenP=this.program(screenVertex,screenFragment);this.postP=this.program(screenVertex,postFragment);
  this.sphere=this.makeSphere();this.ring=this.makeRing(1.22,2.34);this.quad=this.buffer([-1,-1,0,1,-1,0,-1,1,0,-1,1,0,1,-1,0,1,1,0]);this.glow=this.cloud([0,0,0],[1,.4,.095],[9500]);this.blueGlow=this.cloud([0,0,0],[.34,.58,1],[7000]);this.whiteTexture=this.makeTexture();this.rt=gl.createFramebuffer();this.rtTexture=gl.createTexture();this.rtDepth=gl.createRenderbuffer();this.setMode(mode);
  if(interactive)this.bindControls();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas);this.resize();
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.failed=true;canvas.parentElement.classList.add('no-webgl')});
  this.observer=new IntersectionObserver(es=>{this.visible=es[0].isIntersecting},{rootMargin:'120px'});this.observer.observe(canvas);this.visible=true;
  this.frame=t=>{if(this.visible&&!this.failed&&!document.hidden){let dt=Math.min((t-(this.last||t))/1000,.06);if(!this.paused){this.time+=dt*this.speed;this.visualTime+=dt*(['blackhole','galaxy','nebula'].includes(this.mode)?this.speed/12:1);if(this.cinematic&&!this.drag)this.az+=dt*.045;}if(!this.drag){this.az+=this.velAz;this.pitch=Math.max(-1.48,Math.min(1.48,this.pitch+this.velPitch));this.velAz*=.90;this.velPitch*=.90;}this.cameraAz+=(this.az-this.cameraAz)*.15;this.cameraPitch+=(this.pitch-this.cameraPitch)*.15;this.cameraDistance+=(this.distance-this.cameraDistance)*.11;this.render();if(this.onFrame&&t-(this.hudTime||0)>120){this.hudTime=t;this.onFrame(this)}}this.last=t;this.raf=requestAnimationFrame(this.frame)};this.raf=requestAnimationFrame(this.frame);
 }
 program(vs,fs){let g=this.gl,p=g.createProgram();for(const [type,src]of[[g.VERTEX_SHADER,vs],[g.FRAGMENT_SHADER,fs]]){let s=g.createShader(type);g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));g.attachShader(p,s);g.deleteShader(s)}g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));this.programCache.set(p,{attrs:{},uniforms:{}});return p}
 buffer(data){let g=this.gl,b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);return b}
 makeSphere(){let p=[],n=[],s=80,t=56;for(let j=0;j<t;j++)for(let i=0;i<s;i++)for(let[a,b]of[[i,j],[i+1,j],[i,j+1],[i+1,j],[i+1,j+1],[i,j+1]]){let u=a/s*TAU,v=b/t*Math.PI,q=[Math.sin(v)*Math.cos(u),Math.cos(v),Math.sin(v)*Math.sin(u)];p.push(...q);n.push(...q)}return{p:this.buffer(p),n:this.buffer(n),count:p.length/3}}
 makeRing(inner,outer){let p=[],n=[];for(let i=0;i<240;i++)for(let[j,r]of[[i,inner],[i,outer],[i+1,inner],[i,outer],[i+1,outer],[i+1,inner]]){p.push(Math.cos(j/240*TAU)*r,0,Math.sin(j/240*TAU)*r);n.push(0,1,0)}return{p:this.buffer(p),n:this.buffer(n),count:p.length/3}}
 cloud(p,c,s){return{p:this.buffer(p),c:this.buffer(c),s:this.buffer(s),count:s.length}}
 deleteCloud(cloud){if(cloud)for(let key of ['p','c','s'])this.gl.deleteBuffer(cloud[key])}
 makeTexture(){let g=this.gl,t=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,1,1,0,g.RGBA,g.UNSIGNED_BYTE,new Uint8Array([128,128,128,255]));g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);return t}
 texture(name){if(!name)return null;if(!this.textures.has(name)){let record={texture:this.makeTexture(),ready:false};this.textures.set(name,record);const image=astroImage('assets/textures/'+name);const upload=()=>{if(this.disposed)return;let g=this.gl;g.bindTexture(g.TEXTURE_2D,record.texture);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,image);let w=image.naturalWidth,h=image.naturalHeight;let pot=w>0&&h>0&&(w&(w-1))===0&&(h&(h-1))===0;if(pot)g.generateMipmap(g.TEXTURE_2D);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,pot?g.LINEAR_MIPMAP_LINEAR:g.LINEAR);record.ready=true};if(image.complete&&image.naturalWidth)upload();else image.addEventListener('load',upload,{once:true});}return this.textures.get(name)}
 setMode(mode){this.mode=mode;this.time=0;this.visualTime=0;this.focus=false;this.param=mode==='transit'?.1:1;this.distance=({solar:64,blackhole:25,binary:30,galaxy:48,nebula:30,transit:25})[mode];this.az=mode==='transit'?0:.35;this.pitch=mode==='transit'?0:mode==='blackhole'?.075:mode==='galaxy'?.65:.45;this.cameraAz=this.az;this.cameraPitch=this.pitch;this.cameraDistance=this.distance;this.selected=mode==='solar'?'Earth':null;this.velAz=0;this.velPitch=0;if(this.labels)this.labels.innerHTML='';this.deleteCloud(this.particles);this.deleteCloud(this.dust);this.deleteCloud(this.haze);this.particles=this.dust=this.haze=null;
  let r=seeded(492),p=[],c=[],s=[],dp=[],dc=[],ds=[],hp=[],hc=[],hs=[];let gaussian=()=>Math.sqrt(-2*Math.log(Math.max(r(),.00001)))*Math.cos(r()*TAU);
  if(mode==='galaxy'){
   let count=this.interactive?48000:17000;for(let i=0;i<count;i++){let bulge=i<count*.25,rad=bulge?Math.abs(gaussian())*2.0:Math.pow(r(),.64)*17;let arm=i%4,a=bulge?r()*TAU:arm*TAU/4+Math.log(rad+1)*2.6+gaussian()*(.10+.018*rad);let y=gaussian()*(bulge?.8:.17);p.push(rad*Math.cos(a),y,rad*Math.sin(a));let bright=Math.pow(r(),3),inner=Math.exp(-rad/3.);c.push(.33+inner*.55+bright*.45,.42+inner*.22+bright*.42,.65-inner*.24+bright*.38);s.push(18+bright*120);}
   for(let i=0;i<1400;i++){let rad=Math.pow(r(),.5)*16,a=(i%4)*TAU/4+Math.log(rad+1)*2.6+.12+gaussian()*.10;dp.push(rad*Math.cos(a),gaussian()*.22,rad*Math.sin(a));dc.push(.012,.009,.019);ds.push(350+r()*520);hp.push(rad*Math.cos(a-.17),gaussian()*.2,rad*Math.sin(a-.17));hc.push(.018,.030,.068);hs.push(250+r()*600)}
   this.dust=this.cloud(dp,dc,ds);this.haze=this.cloud(hp,hc,hs);
  }
  if(mode==='solar')for(let i=0;i<(this.interactive?3200:700);i++){let a=r()*TAU,au=2.2+r()*1.1,rad=this.orbitScale(au);p.push(Math.cos(a)*rad,(r()-.5)*.5,Math.sin(a)*rad);let q=.15+r()*.2;c.push(q*.8,q*.74,q*.7);s.push(13+r()*40)}
  if(p.length)this.particles=this.cloud(p,c,s);this.resize();
 }
 resize(){if(!this.gl)return;let r=this.canvas.getBoundingClientRect(),base=this.interactive?Math.min(devicePixelRatio||1,1.5):1;let heavy=this.mode==='blackhole'||this.mode==='nebula';let d=base*(heavy?.8:1)*this.quality;this.w=Math.max(1,r.width);this.h=Math.max(1,r.height);let width=Math.max(1,Math.round(this.w*d)),height=Math.max(1,Math.round(this.h*d));this.dpr=d;if(this.canvas.width!==width||this.canvas.height!==height||!this.rtReady){this.canvas.width=width;this.canvas.height=height;let g=this.gl;if(!this.rt)return;g.bindTexture(g.TEXTURE_2D,this.rtTexture);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,width,height,0,g.RGBA,g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.bindRenderbuffer(g.RENDERBUFFER,this.rtDepth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT16,width,height);g.bindFramebuffer(g.FRAMEBUFFER,this.rt);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.rtTexture,0);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,this.rtDepth);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw Error('Render target is incomplete');g.bindFramebuffer(g.FRAMEBUFFER,null);this.rtReady=true;}}
 bindControls(){let el=this.canvas;this.pointers=new Map();el.addEventListener('pointerdown',e=>{if(e.button!==0)return;this.pointers.set(e.pointerId,[e.clientX,e.clientY]);this.drag=true;this.moved=0;this.velAz=this.velPitch=0;this.px=e.clientX;this.py=e.clientY;el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!this.pointers.has(e.pointerId))return;let prev=[...this.pointers.values()];this.pointers.set(e.pointerId,[e.clientX,e.clientY]);if(this.pointers.size===2){let now=[...this.pointers.values()],a=Math.hypot(prev[0][0]-prev[1][0],prev[0][1]-prev[1][1]),b=Math.hypot(now[0][0]-now[1][0],now[0][1]-now[1][1]);this.distance=Math.max(2.3,Math.min(650,this.distance*a/Math.max(1,b)));this.onZoom?.(this.distance);this.moved=100;return}let x=e.clientX-this.px,y=e.clientY-this.py;this.moved+=Math.abs(x)+Math.abs(y);this.velAz=-x*.0045;this.velPitch=y*.0045;this.az+=this.velAz;this.pitch=Math.max(-1.48,Math.min(1.48,this.pitch+this.velPitch));this.px=e.clientX;this.py=e.clientY});el.addEventListener('pointerup',e=>{this.pointers.delete(e.pointerId);this.drag=this.pointers.size>0;if(this.moved<6&&this.mode==='solar'){let r=el.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let hit=(this.hits||[]).filter(h=>PLANETS.some(p=>p.name===h.name)).sort((a,b)=>a.w-b.w).find(h=>Math.hypot(h.x-x,h.y-y)<Math.max(18,h.radius));if(hit){this.selected=hit.name;this.onSelect?.(hit.name)}}});el.addEventListener('pointercancel',e=>{this.pointers.delete(e.pointerId);this.drag=false});el.addEventListener('wheel',e=>{e.preventDefault();this.distance=Math.max(2.3,Math.min(650,this.distance*Math.exp(e.deltaY*.001)));this.onZoom?.(this.distance)},{passive:false});el.addEventListener('keydown',e=>{let handled=true;if(e.key==='ArrowLeft')this.az-=.12;else if(e.key==='ArrowRight')this.az+=.12;else if(e.key==='ArrowUp')this.pitch=Math.min(1.48,this.pitch+.1);else if(e.key==='ArrowDown')this.pitch=Math.max(-1.48,this.pitch-.1);else if(e.key==='+')this.distance=Math.max(2.3,this.distance*.88);else if(e.key==='-')this.distance=Math.min(650,this.distance*1.12);else handled=false;if(handled){e.preventDefault();this.onZoom?.(this.distance)}})}
 use(p){let g=this.gl;if(this.activeProgram!==p){for(let loc of this.enabledAttrs)g.disableVertexAttribArray(loc);this.enabledAttrs.clear();this.activeProgram=p;}g.useProgram(p)}
 attr(p,name,b,size){let g=this.gl,cache=this.programCache.get(p).attrs;if(!(name in cache))cache[name]=g.getAttribLocation(p,name);let loc=cache[name];if(loc<0)return;g.bindBuffer(g.ARRAY_BUFFER,b);g.enableVertexAttribArray(loc);this.enabledAttrs.add(loc);g.vertexAttribPointer(loc,size,g.FLOAT,false,0,0)}
 location(p,k){let cache=this.programCache.get(p).uniforms;if(!(k in cache))cache[k]=this.gl.getUniformLocation(p,k);return cache[k]}
 uniform(p,k,v){let g=this.gl,l=this.location(p,k);if(typeof v==='number')g.uniform1f(l,v);else if(v.length===16)g.uniformMatrix4fv(l,false,v);else g.uniform3fv(l,v)}
 mesh(mesh,p,s,color,kind,{y=0,tilt=0,alpha=1,light=[0,0,0],map=null}={}){let g=this.gl,pr=this.meshP;this.use(pr);this.attr(pr,'aPos',mesh.p,3);this.attr(pr,'aNormal',mesh.n,3);let tex=this.texture(map),night=kind===2?this.texture('earth-night.png'):null;g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,tex?.ready?tex.texture:this.whiteTexture);g.uniform1i(this.location(pr,'uMap'),0);g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,night?.ready?night.texture:this.whiteTexture);g.uniform1i(this.location(pr,'uNight'),1);for(let[k,v]of Object.entries({uVP:this.vp,uModel:M.model(p,s,y,tilt),uColor:color,uKind:kind,uTime:this.visualTime,uAlpha:alpha,uLight:light,uEye:this.eye,uCenter:p,uRadius:s,uHasTexture:tex?.ready?1:0,uHasNight:night?.ready?1:0}))this.uniform(pr,k,v);g.drawArrays(g.TRIANGLES,0,mesh.count)}
 points(cloud,model=M.model(),{swirl=0,additive=true}={}){if(!cloud)return;let g=this.gl,p=this.pointP;this.use(p);this.attr(p,'aPos',cloud.p,3);this.attr(p,'aColor',cloud.c,3);this.attr(p,'aSize',cloud.s,1);for(let[k,v]of Object.entries({uVP:this.vp,uModel:model,uPixel:this.dpr*this.h/550,uTime:this.visualTime,uSwirl:swirl}))this.uniform(p,k,v);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,additive?g.ONE:g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);g.drawArrays(g.POINTS,0,cloud.count);g.depthMask(true);g.disable(g.BLEND)}
 line(points,color=[.15,.23,.3],alpha=1){let g=this.gl;if(!this.lineBuffer)this.lineBuffer=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,this.lineBuffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(points),g.DYNAMIC_DRAW);let pr=this.meshP;this.use(pr);this.attr(pr,'aPos',this.lineBuffer,3);this.attr(pr,'aNormal',this.lineBuffer,3);for(let[k,v]of Object.entries({uVP:this.vp,uModel:M.model(),uColor:color,uKind:11,uTime:0,uAlpha:alpha,uLight:[0,0,0],uEye:this.eye,uCenter:[0,0,0],uRadius:1,uHasTexture:0,uHasNight:0}))this.uniform(pr,k,v);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.drawArrays(g.LINE_STRIP,0,points.length/3);g.disable(g.BLEND)}
 screen(){let g=this.gl,p=this.screenP;this.use(p);this.attr(p,'aPos',this.quad,3);this.spacing=Math.pow(10,Math.floor(Math.log10(this.cameraDistance/10)));for(let[k,v]of Object.entries({uEye:this.eye,uRight:this.right,uUp:this.up,uForward:this.forward,uResolution:[this.canvas.width,this.canvas.height,0],uScene:this.mode==='blackhole'?1:this.mode==='nebula'?2:this.mode==='galaxy'?3:0,uTime:this.visualTime,uDistance:this.cameraDistance,uGrid:this.grid?1:0,uGridStyle:this.gridStyle,uSpacing:this.spacing,uLens:this.lensing?1:0,uDoppler:this.doppler?1:0,uDensity:this.density,uBand:this.band,uSteps:this.interactive?179:140}))this.uniform(p,k,v);g.disable(g.DEPTH_TEST);g.drawArrays(g.TRIANGLES,0,6);g.enable(g.DEPTH_TEST)}
 post(){let g=this.gl,p=this.postP;g.bindFramebuffer(g.FRAMEBUFFER,null);g.viewport(0,0,this.canvas.width,this.canvas.height);g.disable(g.DEPTH_TEST);g.disable(g.BLEND);this.use(p);this.attr(p,'aPos',this.quad,3);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.rtTexture);g.uniform1i(this.location(p,'uSceneMap'),0);this.uniform(p,'uResolution',[this.canvas.width,this.canvas.height,0]);this.uniform(p,'uBloom',this.bloom);this.uniform(p,'uExposure',this.exposure);g.drawArrays(g.TRIANGLES,0,6)}
 project(pos){let m=this.vp,[x,y,z]=pos,w=m[3]*x+m[7]*y+m[11]*z+m[15];return{x:(m[0]*x+m[4]*y+m[8]*z+m[12])/w*this.w/2+this.w/2,y:-(m[1]*x+m[5]*y+m[9]*z+m[13])/w*this.h/2+this.h/2,w}}
 orbitScale(a){return this.linearScale?a*4:3.3+Math.log1p(a/.38)*4.1}
 orbitState(i,day){let p=PLANETS[i],mean=(day/p.period*TAU+i*1.47)%TAU,E=mean;for(let k=0;k<8;k++)E-=(E-p.e*Math.sin(E)-mean)/(1-p.e*Math.cos(E));let r=p.a*(1-p.e*Math.cos(E));return{E,r,speed:Math.sqrt(1.32712440018e11*(2/(r*149597870.7)-1/(p.a*149597870.7))),anomaly:Math.atan2(Math.sqrt(1-p.e*p.e)*Math.sin(E),Math.cos(E)-p.e)}}
 orbit(i,day){let p=PLANETS[i],{E}=this.orbitState(i,day),a=this.orbitScale(p.a),x=a*(Math.cos(E)-p.e),z=a*Math.sqrt(1-p.e*p.e)*Math.sin(E),inc=PLANET_INCLINATIONS[i]*Math.PI/180,node=PLANET_NODES[i]*Math.PI/180;return[x*Math.cos(node)-z*Math.cos(inc)*Math.sin(node),z*Math.sin(inc),x*Math.sin(node)+z*Math.cos(inc)*Math.cos(node)]}
 label(name,pos,radius){let q=this.project(pos);if(q.w<=.01||q.x<0||q.x>this.w||q.y<0||q.y>this.h)return;this.hits.push({...q,name,radius:radius*this.h/q.w/0.7528});if(!this.labels||!this.showLabels)return;let l=this.labels.querySelector('[data-name="'+name+'"]');if(!l){l=document.createElement('span');l.dataset.name=name;this.labels.appendChild(l)}l.textContent=name;l.style.display='';l.style.left=q.x+'px';l.style.top=(q.y+radius*this.h/q.w/0.7528+8)+'px';l.classList.toggle('chosen',name===this.selected)}
 atmosphere(pos,size,color){let g=this.gl;g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE);g.depthMask(false);this.mesh(this.sphere,pos,size*1.042,color,10);g.depthMask(true);g.disable(g.BLEND)}
 moons(index,pos,size){let sets=index===2?[['Moon',3.1,.272,27.3217]]:index===4?[['Io',2.8,.095,1.769],['Europa',3.7,.085,3.551],['Ganymede',4.8,.13,7.155],['Callisto',6.3,.12,16.689]]:index===5?[['Titan',4.5,.14,15.945]]:[];for(let [name,d,r,p]of sets){let a=this.time/p*TAU,rr=d*size,moon=[pos[0]+Math.cos(a)*rr,pos[1]+Math.sin(a)*.06*size,pos[2]+Math.sin(a)*rr];this.mesh(this.sphere,moon,size*r,[.65,.6,.5],1,{map:name==='Moon'?'moon.jpg':null,y:a});if(this.paths){let pts=[];for(let i=0;i<=96;i++)pts.push(pos[0]+Math.cos(i/96*TAU)*rr,pos[1],pos[2]+Math.sin(i/96*TAU)*rr);this.line(pts,[.12,.23,.28],.6)}this.label(name,moon,size*r)}}
 render(){let g=this.gl;if(!g||!this.rtReady||this.w<2||this.h<2)return;g.bindFramebuffer(g.FRAMEBUFFER,this.rt);g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(.002,.004,.009,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.enable(g.DEPTH_TEST);g.disable(g.CULL_FACE);let target=this.focus&&this.mode==='solar'?this.orbit(Math.max(0,PLANETS.findIndex(p=>p.name===this.selected)),this.time):[0,0,0];let az=this.cameraAz??this.az,pitch=this.cameraPitch??this.pitch,d=this.cameraDistance??this.distance;this.eye=[Math.sin(az)*Math.cos(pitch)*d,Math.sin(pitch)*d,Math.cos(az)*Math.cos(pitch)*d].map((v,i)=>v+target[i]);this.forward=V.norm(V.sub(target,this.eye));this.right=V.norm(V.cross(this.forward,[0,1,0]));this.up=V.cross(this.right,this.forward);this.vp=M.mul(M.perspective(.72,this.w/this.h,.025,5000),M.look(this.eye,target));this.screen();this.hits=[];if(this.labels){this.labels.hidden=!this.showLabels;this.labels.querySelectorAll('span').forEach(l=>l.style.display='none')}
  if(this.mode==='solar'){
   let factor=this.linearScale?.18:1;this.points(this.glow);this.mesh(this.sphere,[0,0,0],1.15*factor,[1,.48,.055],0,{map:'sun.jpg',y:this.visualTime*.013});this.label('Sun',[0,0,0],1.15*factor);
   PLANETS.forEach((p,i)=>{let size=p.size*factor,pos=this.orbit(i,this.time);if(this.paths){let pts=[];for(let k=0;k<=180;k++)pts.push(...this.orbit(i,k/180*p.period-i*1.47/TAU*p.period));this.line(pts,p.name===this.selected?[.27,.62,.61]:[.12,.20,.27],p.name===this.selected?.9:.48)}this.mesh(this.sphere,pos,size,p.color,p.kind,{y:this.visualTime*(i===1?-.018:.04)+i,tilt:PLANET_TILTS[i]*Math.PI/180,map:PLANET_MAPS[i]+'.jpg'});if([1,2,4,5,6,7].includes(i))this.atmosphere(pos,size,i===2?[.16,.43,1]:i===4||i===5?[.43,.32,.19]:[.15,.35,.60]);if(i===2){g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);this.mesh(this.sphere,pos,size*1.012,[1,1,1],9,{y:this.visualTime*.048,tilt:.409});g.disable(g.BLEND)}if(i===5){g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);this.mesh(this.ring,pos,size,[.83,.72,.51],7,{tilt:.466,alpha:.89,map:'saturn-rings.png'});g.disable(g.BLEND)}this.label(p.name,pos,size);if(this.focus&&p.name===this.selected)this.moons(i,pos,size);if(this.vector&&p.name===this.selected){let next=this.orbit(i,this.time+.03),v=V.norm(V.sub(next,pos)),tip=pos.map((x,j)=>x+v[j]*size*4);this.line([...pos,...tip],[.4,1,.71]);this.label('Velocity',tip,0)}});if(!this.linearScale)this.points(this.particles,M.model(),{swirl:.025});
  }else if(this.mode==='binary'){
   let q=this.param,sep=10,period=Math.sqrt(1000/(1+q))*365.25,a=this.time/period*TAU,one=[Math.cos(a)*sep*q/(1+q),0,Math.sin(a)*sep*q/(1+q)],two=[-Math.cos(a)*sep/(1+q),0,-Math.sin(a)*sep/(1+q)];if(this.paths)for(let rad of [sep*q/(1+q),sep/(1+q)]){let pts=[];for(let i=0;i<=180;i++)pts.push(Math.cos(i/180*TAU)*rad,0,Math.sin(i/180*TAU)*rad);this.line(pts,[.2,.34,.45],.75)}this.points(this.glow,M.model(one));this.points(this.blueGlow,M.model(two));this.mesh(this.sphere,one,1.1,[1,.43,.065],0,{map:'sun.jpg',y:this.visualTime*.04});this.mesh(this.sphere,two,Math.pow(q,.55)*.82,[.34,.61,1.],0,{y:this.visualTime*.065});this.label('Primary · 1 M☉',one,1.1);this.label('Companion',two,Math.pow(q,.55)*.82);this.line([-.2,0,0,.2,0,0],[.5,.8,.75]);this.line([0,0,-.2,0,0,.2],[.5,.8,.75]);this.label('Barycenter',[0,0,0],0);
  }else if(this.mode==='galaxy'){this.points(this.haze,M.model(),{swirl:.055});this.points(this.particles,M.model(),{swirl:.055});
  }else if(this.mode==='transit'){
   this.points(this.glow);this.mesh(this.sphere,[0,0,0],2.7,[1,.54,.13],0,{map:'sun.jpg',y:this.visualTime*.014});let a=this.time*.017,pos=[9*Math.sin(a),this.impact*2.7*Math.cos(a),Math.sqrt(81-Math.pow(this.impact*2.7,2))*Math.cos(a)];this.mesh(this.sphere,pos,2.7*this.param,[.18,.3,.55],1,{map:'neptune.jpg',y:this.visualTime*.05});this.atmosphere(pos,2.7*this.param,[.14,.36,.65]);if(this.paths){let pts=[];for(let i=0;i<=180;i++)pts.push(Math.sin(i/180*TAU)*9,this.impact*2.7*Math.cos(i/180*TAU),Math.cos(i/180*TAU)*Math.sqrt(81-Math.pow(this.impact*2.7,2)));this.line(pts,[.15,.28,.33],.6)}this.label('Exoplanet',pos,2.7*this.param);}
  this.post();
 }
 destroy(){this.disposed=true;cancelAnimationFrame(this.raf);this.resizeObserver?.disconnect();this.observer?.disconnect();this.gl?.getExtension('WEBGL_lose_context')?.loseContext()}
}
