/* Scientific controls, camera bookmarks, and computed observables. */
function factRow(name,value,id=''){return `<div class="fact"><span>${name}</span><b ${id?`id="${id}"`:''}>${value}</b></div>`}
function labRange(id,label,min,max,step,value,output=''){return `<div class="slider-control lab-range"><label for="${id}">${label}<output id="${id}-value">${output||value}</output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`}
function renderInspector(){
 if(!sim||sim.failed)return;let m=MODES.find(x=>x.id===currentMode),html='';
 if(currentMode==='solar'){
  let p=PLANETS.find(x=>x.name===sim.selected)||PLANETS[2],i=PLANETS.indexOf(p);
  html=`<div class="eyebrow">PLANETARY EXPLORER</div><select class="object-select" id="object-select" aria-label="Choose a celestial object">${PLANETS.map(x=>`<option ${x.name===p.name?'selected':''}>${x.name}</option>`).join('')}</select><h3>${p.name}</h3><p>${p.fact}</p><div class="science-readout"><span>INSTANTANEOUS ORBITAL SPEED</span><strong id="live-speed">—</strong><small>km/s · two-body approximation</small></div><div class="facts">${factRow('Distance from Sun','—','live-radius')}${factRow('Mean diameter',p.diameter)}${factRow('Orbital period',p.period>1000?(p.period/365.25).toFixed(2)+' yr':p.period.toFixed(2)+' d')}${factRow('Eccentricity',p.e.toFixed(3))}${factRow('Inclination',PLANET_INCLINATIONS[i].toFixed(3)+'°')}</div><button class="btn primary" data-action="focus-object">${icon('search')}Follow ${p.name}</button><p class="inspector-caption">Follow Earth, Jupiter, or Saturn to reveal their modeled moons. Surface rotation is slowed for viewing.</p>`;
 }else if(currentMode==='blackhole'){
  html=`<div class="eyebrow">GRAVITY & LIGHT</div><h3>A bent view of reality.</h3><p>Trace light past a compact object. Turn bending off to compare the distorted disk with its ordinary geometric view.</p><div class="science-readout warm"><span>SCHWARZSCHILD RADIUS</span><strong id="radius-label">${(sim.param*29.53).toFixed(1)} <em>km</em></strong><small>rₛ = 2GM/c² · nonrotating limit</small></div><div class="facts">${factRow('Mass',(sim.param*10).toFixed(0)+' M☉','mass-label')}${factRow('Photon sphere','1.5 rₛ')}${factRow('ISCO','3 rₛ')}${factRow('View scale','Normalized to rₛ')}</div>${labRange('scene-param','Mass / solar masses',.3,10,.1,sim.param,(sim.param*10).toFixed(0))}<label class="lab-switch"><input id="lens-toggle" type="checkbox" ${sim.lensing?'checked':''}>Light bending</label><label class="lab-switch"><input id="doppler-toggle" type="checkbox" ${sim.doppler?'checked':''}>Doppler brightness asymmetry</label><p class="inspector-caption">The image is mass-invariant in rₛ units. Mass changes the physical size, not its normalized appearance.</p>`;
 }else if(currentMode==='binary'){
  html=`<div class="eyebrow">BINARY-STAR DYNAMICS</div><h3>Gravity in balance.</h3><p>Change the mass ratio and measure the primary star’s line-of-sight velocity. Rotating the view changes the projected signal.</p><div class="science-readout"><span>PRIMARY RADIAL VELOCITY</span><strong id="live-rv">—</strong><small>km/s · positive means receding</small></div><div id="live-chart" class="science-chart"></div><div class="facts">${factRow('Primary mass','1.00 M☉')}${factRow('Companion mass',sim.param.toFixed(2)+' M☉','mass-label')}${factRow('Separation','10 AU')}${factRow('Orbital period',Math.sqrt(1000/(1+sim.param)).toFixed(2)+' yr','period-label')}</div>${labRange('scene-param','Companion / primary mass',.1,3,.05,sim.param,sim.param.toFixed(2))}`;
 }else if(currentMode==='transit'){
  html=`<div class="eyebrow">EXOPLANET PHOTOMETRY</div><h3>A world in one percent.</h3><p>Measure a modeled transit. Planet size, grazing geometry, and stellar limb darkening all change its shape.</p><div class="science-readout"><span>MODEL TRANSIT DEPTH</span><strong id="depth-label">—</strong><small>Numerically integrated stellar disk</small></div><div id="live-chart" class="science-chart"></div>${labRange('scene-param','Planet / star radius',.03,.3,.01,sim.param,sim.param.toFixed(2))}${labRange('impact','Impact parameter b',0,1.4,.02,sim.impact,sim.impact.toFixed(2))}${labRange('limb','Limb darkening u',0,.9,.05,sim.limbDarkening,sim.limbDarkening.toFixed(2))}<div class="facts">${factRow('Current relative flux','—','live-flux')}${factRow('Photometry observer','Fixed +Z direction')}</div><p class="inspector-caption">I(μ) = I₀ [1 − u(1 − μ)]. Moving the camera does not change the photometry observer.</p>`;
 }else if(currentMode==='galaxy'){
  html=`<div class="eyebrow">GALACTIC STRUCTURE</div><h3>A city made of suns.</h3><p>A stellar bulge, a thin disk, structured dust, and blue spiral arms. The tracer stars shear at different angular speeds.</p><div class="science-readout"><span>STELLAR TRACERS</span><strong>48,000</strong><small>Synthetic population · four spiral arms</small></div><div class="facts">${factRow('Rotation law','Ω ∝ 1 / (R + 2)')}${factRow('Central population','Warm stellar bulge')}${factRow('Dust structure','Attenuating arm lanes')}${factRow('Reference','Illustrative galaxy')}</div><p class="inspector-caption">This is an advected tracer model with an analytic volume. It does not solve self-gravity or density-wave dynamics.</p>`;
 }else{
  html=`<div class="eyebrow">VOLUMETRIC OBSERVATORY</div><h3>Light through the dust.</h3><p>Look through a continuous 3D density field. Dense filaments absorb light while illuminated gas glows around embedded stars.</p><div class="science-readout rose"><span>YOUR OBSERVING PALETTE</span><strong style="font-size:23px" id="band-label">${sim.band?'Warm dust / cool gas':'Hydrogen / oxygen'}</strong><small>Illustrative false-color mapping</small></div>${labRange('density','Relative cloud density',.3,2.8,.1,sim.density,sim.density.toFixed(1)+'×')}<label class="lab-select">Color mapping<select id="band-select" class="object-select"><option value="0" ${!sim.band?'selected':''}>Hydrogen / oxygen inspired</option><option value="1" ${sim.band?'selected':''}>Warm dust / cool gas</option></select></label><div class="facts">${factRow('Density field','Multiscale, continuous')}${factRow('Light model','Emission + absorption')}${factRow('View','Orbit through 3D')}</div><p class="inspector-caption">These colors illustrate structure. They are not calibrated spectral observations of an actual nebula.</p>`;
 }
 $('#inspector').innerHTML=html+`<button class="text-link science-link" data-article="${m.article}">${icon('book')}Explore the underlying science ${icon('arrow')}</button>`;
 $('#object-select')?.addEventListener('change',e=>{sim.selected=e.target.value;renderInspector()});
 $('#scene-param')?.addEventListener('input',e=>{sim.param=Number(e.target.value);$('#scene-param-value').textContent=currentMode==='blackhole'?(sim.param*10).toFixed(0):sim.param.toFixed(2);if(currentMode==='blackhole'){$('#radius-label').innerHTML=(sim.param*29.53).toFixed(1)+' <em>km</em>';$('#mass-label').textContent=(sim.param*10).toFixed(0)+' M☉'}if(currentMode==='binary'){$('#mass-label').textContent=sim.param.toFixed(2)+' M☉';$('#period-label').textContent=Math.sqrt(1000/(1+sim.param)).toFixed(2)+' yr'}updateLiveChart();updateLabHUD()});
 $('#lens-toggle')?.addEventListener('change',e=>sim.lensing=e.target.checked);$('#doppler-toggle')?.addEventListener('change',e=>sim.doppler=e.target.checked);
 $('#impact')?.addEventListener('input',e=>{sim.impact=Number(e.target.value);$('#impact-value').textContent=sim.impact.toFixed(2);updateLiveChart()});$('#limb')?.addEventListener('input',e=>{sim.limbDarkening=Number(e.target.value);$('#limb-value').textContent=sim.limbDarkening.toFixed(2);updateLiveChart()});
 $('#density')?.addEventListener('input',e=>{sim.density=Number(e.target.value);$('#density-value').textContent=sim.density.toFixed(1)+'×'});$('#band-select')?.addEventListener('change',e=>{sim.band=Number(e.target.value);$('#band-label').textContent=sim.band?'Warm dust / cool gas':'Hydrogen / oxygen'});
 updateLiveChart();updateLabHUD();
}
function plotSVG(points,top,bottom,caption){return `<svg viewBox="0 0 280 135" role="img" aria-label="${caption}"><path d="M15 18H265M15 52H265M15 86H265M15 18V100H265" stroke="#344250" stroke-width=".6" fill="none"/><path d="${points}" stroke="#83e0c6" stroke-width="1.7" fill="none"/><text x="15" y="12">${top}</text><text x="15" y="114">${bottom}</text><text x="265" y="130" text-anchor="end">${caption}</text><circle id="plot-dot" r="3" fill="#f1dbab" cx="15" cy="18"/></svg>`}
function binaryAmplitude(){return 29.7846918*sim.param/Math.sqrt(10*(1+sim.param))*Math.cos(sim.cameraPitch)}
function updateLiveChart(){if(!sim||!$('#live-chart'))return;if(currentMode==='transit'){let depth=1-transitFlux(sim.impact,sim.param,sim.limbDarkening);$('#depth-label').innerHTML=(depth*100).toFixed(3)+'<em> %</em>';let pts=[],max=Math.max(depth,.001);for(let i=0;i<=180;i++){let x=-1.45+i/180*2.9,flux=transitFlux(Math.hypot(x,sim.impact),sim.param,sim.limbDarkening);pts.push((i?'L':'M')+(15+i/180*250).toFixed(2)+' '+(18+(1-flux)/max*65).toFixed(2))}$('#live-chart').innerHTML=plotSVG(pts.join(''),'1.000 relative flux',(1-depth).toFixed(4),'Projected position / R★');}else if(currentMode==='binary'){let pts=[];for(let i=0;i<=120;i++)pts.push((i?'L':'M')+(15+i/120*250).toFixed(2)+' '+(52+34*Math.cos(i/120*TAU)).toFixed(2));$('#live-chart').innerHTML=plotSVG(pts.join(''),'Receding +','Approaching −','Orbital phase →');}}
function updateLabHUD(){if(!sim||sim.failed)return;let put=(id,v)=>{let el=$('#'+id);if(el)el.textContent=v};put('hud-clock',(currentMode==='solar'||currentMode==='binary'?'T + '+sim.time.toFixed(1)+' d':'T + '+sim.visualTime.toFixed(1)+' s'));put('hud-camera',sim.focus?'FOLLOWING '+sim.selected.toUpperCase():'FREE ORBIT');put('hud-grid',sim.grid?'GRID '+(sim.spacing||1).toPrecision(1)+' VIEW UNITS':'COORDINATES OFF');
 if(currentMode==='solar'){let i=Math.max(0,PLANETS.findIndex(p=>p.name===sim.selected)),state=sim.orbitState(i,sim.time);put('live-speed',state.speed.toFixed(2));put('live-radius',state.r.toFixed(3)+' AU')}
 if(currentMode==='binary'){let period=Math.sqrt(1000/(1+sim.param))*365.25,phase=sim.time/period*TAU+sim.cameraAz;put('live-rv',(-binaryAmplitude()*Math.cos(phase)).toFixed(2));let dot=$('#plot-dot');dot?.setAttribute('cx',15+((phase/TAU)%1+1)%1*250);dot?.setAttribute('cy',52+34*Math.cos(phase))}
 if(currentMode==='transit'){let a=sim.time*.017,x=9/2.7*Math.sin(a),z=Math.hypot(x,sim.impact*Math.cos(a)),flux=Math.cos(a)>0?transitFlux(z,sim.param,sim.limbDarkening):1;put('live-flux',flux.toFixed(5));let depth=Math.max(.001,1-transitFlux(sim.impact,sim.param,sim.limbDarkening));let dot=$('#plot-dot');if(dot){dot.setAttribute('cx',15+(x+1.45)/2.9*250);dot.setAttribute('cy',18+(1-flux)/depth*65);dot.style.display=Math.abs(x)<1.45&&Math.cos(a)>0?'':'none'}}
}
function focusPlanet(name){if(!sim)return;sim.selected=name;sim.focus=true;let p=PLANETS.find(x=>x.name===name),pos=sim.orbit(PLANETS.indexOf(p),sim.time);let sunAz=Math.atan2(-pos[0],-pos[2]);sim.az=sunAz+.62;sim.pitch=.25;sim.distance=Math.max(2.3,p.size*(name==='Saturn'?8:6))*(sim.linearScale?.3:1);sim.distance=Math.max(2.3,sim.distance);sim.speed=.7;$('#speed').value=Math.log(sim.speed/.05)/Math.log(100000)*100;$('#speed-value').textContent=speedLabel(sim.speed);updateZoom(sim.distance);renderInspector();}
function renderScenePresets(){let options=currentMode==='solar'?[['overview','System overview'],['earth','Earth & Moon'],['jupiter','Jovian system'],['saturn','Saturn & Titan'],['polar','Polar view']]:currentMode==='blackhole'?[['edge','Edge-on lensing'],['polar','Above the disk'],['inclined','Inclined view']]:currentMode==='galaxy'?[['face','Face-on spiral'],['edge','Edge-on disk'],['inclined','Three-quarter view']]:currentMode==='transit'?[['observer','Photometry observer'],['inclined','Orbital geometry']]:[['overview','Overview'],['polar','Polar view'],['inclined','Immersive angle']];$('#scene-presets').innerHTML=`<span>CAMERA BOOKMARKS</span>${options.map(([id,label])=>`<button data-camera="${id}">${label}</button>`).join('')}`;$('#distance-scale').disabled=currentMode!=='solar';}
function cameraBookmark(id){if(['earth','jupiter','saturn'].includes(id)){focusPlanet(id[0].toUpperCase()+id.slice(1));return}sim.focus=false;sim.velAz=sim.velPitch=0;if(id==='overview'){sim.az=.35;sim.pitch=.45;sim.distance=currentMode==='solar'?(sim.linearScale?350:64):30}if(id==='polar'||id==='face'){sim.pitch=1.45;sim.az=.35;if(currentMode==='solar')sim.distance=sim.linearScale?350:64}if(id==='edge'){sim.pitch=currentMode==='blackhole'?.06:.045;sim.az=.35}if(id==='inclined'){sim.pitch=.55;sim.az=.9}if(id==='observer'){sim.pitch=0;sim.az=0;sim.distance=25}updateZoom(sim.distance);updateLabHUD()}
function initLab(){
 $('#exposure').addEventListener('input',e=>{if(sim)sim.exposure=Number(e.target.value);$('#exposure-value').textContent=Number(e.target.value).toFixed(2)+'×'});
 $('#bloom').addEventListener('input',e=>{if(sim)sim.bloom=Number(e.target.value);$('#bloom-value').textContent=Number(e.target.value).toFixed(2)});
 $('#detail-level').addEventListener('change',e=>{if(sim){sim.quality=Number(e.target.value);sim.resize()}});
 $('#grid-style').addEventListener('change',e=>{if(sim)sim.gridStyle=Number(e.target.value)});
 $('#distance-scale').addEventListener('change',e=>{if(!sim)return;sim.linearScale=e.target.value==='linear';sim.focus=false;sim.distance=sim.linearScale?350:64;updateZoom(sim.distance);updateModelNote()});
 $('#cinematic').addEventListener('change',e=>{if(sim)sim.cinematic=e.target.checked});$('#velocity-vectors').addEventListener('change',e=>{if(sim)sim.vector=e.target.checked});
 document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.camera&&sim)cameraBookmark(b.dataset.camera);if(b.dataset.action==='theater'){document.body.classList.toggle('theater-mode');b.setAttribute('aria-pressed',document.body.classList.contains('theater-mode'));setTimeout(()=>sim?.resize(),60)}});
}
function updateModelNote(){let m=MODES.find(x=>x.id===currentMode);$('#model-note').textContent=m.note+(currentMode==='solar'?(sim?.linearScale?' Linear distance mode: semimajor axes use one common distance scale; body radii remain enlarged.':' Compact mode: distances are logarithmically compressed; the grid is in view units, not AU.'):'');}
